import type { Metadata } from 'next';
import { JetBrains_Mono } from 'next/font/google';

import './globals.css';

import { cn } from '@/lib';

import Layout from '@/components/layouts';
import { GoogleAnalytics } from '@next/third-parties/google';

const sans = JetBrains_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Antoni saputra',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          sans.className,
          'min-h-screen bg-background py-12 sm:py-24 px-6',
        )}
      >
        <Layout>{children}</Layout>
      </body>
      <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_MEASUREMENT_ID!} />
    </html>
  );
}
